# Generated by Django 4.2.30 on 2026-08-18 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatdemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=10, unique=True)),
                ('allocation_id', models.IntegerField()),
                ('used_id', models.IntegerField()),
                ('avialable_id', models.IntegerField(default=1)),
                ('month_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
