# Generated by Django 4.2.30 on 2026-08-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
