# Generated by Django 4.2.30 on 2026-08-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10, unique=True)),
                ('book_name', models.CharField(max_length=20)),
                ('total_book', models.IntegerField()),
                ('book_issue', models.IntegerField()),
                ('book_avl', models.IntegerField()),
            ],
        ),
    ]
