# Generated by Django 4.2.30 on 2026-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=10, unique=True)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_roll', models.IntegerField()),
                ('stu_stream', models.CharField(max_length=10)),
                ('stu_city', models.CharField(max_length=20)),
            ],
        ),
    ]
