# Generated by Django 4.2.30 on 2026-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_degn', models.CharField(max_length=20)),
                ('emp_city', models.CharField(max_length=20)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
