# Generated by Django 4.2.30 on 2026-08-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.CharField(max_length=10)),
                ('bug_allocation', models.IntegerField()),
                ('bug_used', models.IntegerField()),
                ('bug_avl', models.IntegerField()),
                ('bug_month', models.CharField(max_length=10)),
            ],
        ),
    ]
