# Generated by Django 4.2.30 on 2026-09-01 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_email', models.EmailField(max_length=254, unique=True)),
                ('p_phone', models.ImageField(upload_to='')),
                ('p_city', models.CharField(max_length=20)),
                ('p_state', models.CharField(max_length=20)),
                ('p_country', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
