# Generated by Django 4.2.30 on 2026-09-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='p_phone',
            field=models.IntegerField(),
        ),
    ]
