# Generated by Django 4.2.30 on 2026-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_alter_profiles_p_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('b_age', models.IntegerField()),
                ('b_city', models.CharField(max_length=20)),
                ('b_gender', models.CharField(max_length=20)),
                ('b_dob', models.DateField()),
                ('b_pic', models.FileField(blank=True, null=True, upload_to='b_pic/')),
            ],
        ),
    ]
