# Generated by Django 4.2.30 on 2026-09-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_biodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=20)),
                ('r_roll', models.CharField(max_length=10, unique=True)),
                ('r_math', models.IntegerField()),
                ('r_science', models.IntegerField()),
                ('r_english', models.IntegerField()),
                ('r_odia', models.IntegerField()),
                ('r_history', models.IntegerField()),
                ('r_geography', models.IntegerField()),
                ('r_total', models.IntegerField()),
            ],
        ),
    ]
