# Generated by Django 4.2.30 on 2026-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('allocate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grocery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shopping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avl', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
