# Generated by Django 4.2.30 on 2026-09-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='month',
            new_name='e_month',
        ),
    ]
