# Generated by Django 4.2.30 on 2026-09-02 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_rename_month_expense_e_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mob', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('issue', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
