# Generated by Django 4.2.30 on 2026-09-03 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.CharField(max_length=10, unique=True)),
                ('phone_no', models.IntegerField()),
                ('home', models.CharField(max_length=20)),
                ('ac_type', models.CharField(max_length=20)),
                ('ac_no', models.IntegerField()),
                ('pics', models.FileField(blank=True, null=True, upload_to='pics/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
