# Generated by Django 4.2.30 on 2026-09-03 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ac_no', models.IntegerField(unique=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=100)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=100)),
                ('mode', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
