# Generated by Django 4.2.30 on 2026-09-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dress', models.IntegerField()),
                ('shirt', models.IntegerField()),
                ('pant', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
